### PR TITLE
Finish MutationStats Class and untittest

### PR DESCRIPTION
**Pull request by stevenhwu**
Finish MutationStats Class and untittest ￼…
- Carry on from PR #164 and issue #161. Moved all stats in FindMutation to MutationStats
- Currently, call.cc still use stats_t, so all results in MutationStats got assign back to stats_t. Finish this part at the next PR.
- Most of the calculate are in methods start with Calculate***.

### CODE REVIEW

**Comment by reedacartwright** [comment]
Jenkins, retest this please.

**Comment by reedacartwright** [comment]
Jenkins, retest this please.

**Comment by reedacartwright** [comment]
Jenkins, retest this please

**Comment by reedacartwright** [comment]
Jenkins, restest this please

**Comment by reedacartwright** [comment]
Jenkins, retest this please

**Comment by reedacartwright** [comment]
Jenkins, test this please

**Comment by reedacartwright** [comment]
I think we should consider changing in the future the functions in the stats class to return the variable instead of setting a local one.

**Comment by stevenhwu** [comment]
so, as a simple example, instead of 

``` c++
void MutationStats::SetScaledLogLikelihood(double scale) {
    lld_ = static_cast<float>((logdata_ + scale) / M_LN10);
}
```

we want to do something like?

``` c++
double MutationStats::SetScaledLogLikelihood(double scale) {
    double lld = static_cast<float>((logdata_ + scale) / M_LN10);
    return lld;
}
```

and maybe pass the reference for multiple variables

``` c++
void MutationStats::SetScaledLogLikelihood(vector<> &genotype, vector<> &another_long_stats) {
    ....    
}
```

**Pull request merged**
