### PR TITLE
Add tests and R codes for mutation/peeling

### PR DESCRIPTION
**Pull request by stevenhwu**
- This PR contains tests and R codes that can be used for testing multiple inheritance pattern #54.
- Update `Tests/Unit/dng/mutation.cc`. Previously, all expected results are calculated within dng, which is not exactly valid. Now all results are calculated in R (`test_mutation.R`)
  - Add `test_meiosis_haploid_matrix` and  `test_meiosis_diploid_matrix`.
  - TODO: add 4 `test_m**osis_**ploid_mean_matrix` tests and R codes.
- Add `Tests/Unit/dng/relationship_graph_peeling.cc`
  - This test aims to test PeelForwards() function is relationship_graph.h.
  - Now we have R code to test calculated the expected values for each step in the peeling algorithms.
  - Tested on four different mutype=0, -1, 1, 2.
  - R code is in `test_relationship_graph_peeling.R`
  - This will be expanded for testing multiple inheritance pattern #54 later.
  - Maybe `mutype` should be clarify and rename (num_mutation?) at some stage.
- Clean up and refactor some `pedigree/RelationshipGraph` in `Tests/`, related to #85

### CODE REVIEW

**Comment by reedacartwright** [comment]
Jenkins, okay to test

**Review by reedacartwright — CHANGES_REQUESTED** [review]
For maintenance reasons, let's put each of the matrices in its own file and then use #include to bring them into the testing cc file.  E.g.

```
expected_matrix_two <<
#include "expected_matrix_two.txt"
;
```

**Comment by stevenhwu** [comment]
try a sub dir with `*.incl`

**Comment by reedacartwright** [comment]
Features proposed in this pull request have been added in other pulls.

**Pull request closed without merging**
