### PR TITLE
Feature/read groups

### PR DESCRIPTION
**Pull request by kaeldai**
Fix for issue #51 (and possibly #52). User can now specify which SAM @RG tag to use in order to group different libraries together with the option "--lbtag".

### CODE REVIEW

**Comment by reedacartwright** [comment]
Jenkins, ok to test

**Comment by reedacartwright** [comment]
I think `--rgtag` or `--rg-tag` is better than `--lbtag`.

**Comment by reedacartwright** [comment]
We describe `--rgtag` as "SAM read group header tag to uniquely identify libraries."  I think that needs to have a better description.

**Comment by kaeldai** [comment]
"Combine samples using @RG tags [ID|SM|LB|DS|FO|PG|PL|PU|PM]"

Courtesy of Rachel and Steven.

**Comment by reedacartwright** [comment]
Since we don't combine samples.  It is better to say "Combine read groups ..."

"Combine read groups using @RG tags, e.g. ID, SM, or LB."

**Pull request merged**
