### PR TITLE
Refactor peeling.cc and add tests associate with it

### PR DESCRIPTION
**Pull request by stevenhwu**
Issue #80
Refactor peeling.cc, forward only
- add up_core() and to_parent_core() to simplify the code.
- Add a few utility functions, such as sum_over_children(), multiply_upper_lower(). Some might change after refactor reverse functions.

Add 3 boost_test
- test_sum_over_child
- test_up_core
- test_down

TODO:
- Some of these might be better in struct workspace_t
- Better check/testing for "family" can be parent-child or Dad-mom-child
- Check reverse functions
- Some debug codes might be redundant

### CODE REVIEW

**Comment by reedacartwright** [comment]
Jenkins, ok to test

**Comment by reedacartwright** [comment]
@stevenhwu Have you tested the performance of your changes?  Eigen does the best when more operations are on the same line because it can optimize them efficiently.

**Comment by stevenhwu** [comment]
Thanks, good to know that's how Eigen works. Ran some quick (incompletely) tests, the difference is like 2s in millions of calls. Push the new test case soon.
TODO:
- Update them if these are the bottleneck
- Make it Eigen fast and without redundancy

**Comment by stevenhwu** [comment]
Update peeling.cc to ensure performance.
Based on 10 Millions calls, the difference ~ +- 2%. 
TODO: better test dir layout #85

**Comment by stevenhwu** [comment]
Update peeling.cc. Some eigen related functions are defined in macro to ensure speed.
Based on 10 Millions calls or randomly generated dataset, the difference ~ +- 2%.

**Pull request closed without merging**
