### PR TITLE
Explain the relationship of the 12 members graph

### PR DESCRIPTION
**Pull request by stevenhwu**
- These two figures help us to work out the expected results for unittest `relationship_graph_2.cc`, the 12 member relationship graph. This is the graphical representation of `testdata/relationship_graph/relationship_graph.ped`.
- Several things should be considered before merging
  - Where should we put this file?
  - What other information do we want to include here.
  - Naming convention, later on we might have 50 members graph.

### CODE REVIEW

**Comment by kaeldai** [comment]
retest this please

**Comment by reedacartwright** [comment]
In pedigrees, most individuals are known by IDs. Unless you are working with some well studied charismatic group of animals.

Pedigrees are typically labeled by generation and individual number: e.g. II-3 and V-6. Using Roman numbers will probably complicate things, but we can use Letters and numbers: B3 and E6.

**Comment by reedacartwright** [comment]
Jenkins, retest this please

**Comment by reedacartwright** [comment]
Jenkins, retest this please.

**Comment by reedacartwright** [comment]
Jenkins, retest this please

**Comment by reedacartwright** [comment]
Jenkins, retest this please

**Comment by reedacartwright** [comment]
Jenkins, test this please

**Comment by anderspitman** [comment]
The pdf has a typo in the filename

**Review by reedacartwright — CHANGES_REQUESTED** [review]
For now, let's put this information in a `Tests/doc` directory

**Pull request merged**
