### PR TITLE
Feature/jenkins

### PR DESCRIPTION
**Pull request by kaeldai**
Modified and added to test/ directory to include some initial Boost unit tests. Also added sub-directory CMakeLists.txt that will take care of both unit testing and full executable testing.

### CODE REVIEW

**Comment by reedacartwright** [comment]
okay to test

**Comment by reedacartwright** [comment]
okay to test

**Comment by reedacartwright** [comment]
okay to test

**Comment by reedacartwright** [comment]
okay to test

**Comment by reedacartwright** [comment]
test this please

**Comment by reedacartwright** [comment]
retest this please

**Comment by reedacartwright** [comment]
retest this please

**Comment by reedacartwright** [comment]
okay to test

**Comment by reedacartwright** [comment]
retest this please

**Comment by reedacartwright** [comment]
retest this please

**Comment by reedacartwright** [comment]
retest this please

**Comment by reedacartwright** [comment]
retest this please

**Comment by reedacartwright** [comment]
retest this please

**Comment by reedacartwright** [comment]
retest this please

**Comment by reedacartwright** [comment]
@kaeldai How does BUILD_EXTERNAL_DEPENDENCIES interact with this?

**Comment by kaeldai** [comment]
There shouldn't be any interaction between the ctest files and BUILD_EXTERNAL_DEPENDENCIES. The tests should only be run after calling cmake && make. If cmake/make cannot build dng-call, the it will not be able to build the tests.

**Comment by kaeldai** [comment]
I should add some clarification to the README file.

**Pull request merged**
