### PR TITLE
Adding Treecall

### PR DESCRIPTION
**Pull request by rachelss**
This is a new feature for denovogear. Treecall is from https://github.com/nh3/treecall . Installation is now integrated in cmake. The python script to run treecall is now an installed executable run as with other dng features (i.e. dng treecall). The extra scripts are installed in a package inside the dng installation folder. The python package py-editdist (old version for 2.7) is also installed in this location (treecall depends on it). Running the usual cmake/make/install commands will install treecall and dependencies as is done for other dng features.

### CODE REVIEW

**Comment by kaeldai** [comment]
jenkins, ok to test.

**Comment by reedacartwright** [comment]
Jenkins, ok to test.

**Comment by reedacartwright** [comment]
@rachelss  Can you pull from the develop branch to make sure you are up to date?

**Comment by reedacartwright** [comment]
@rachelss We need more details in your PR message.

**Comment by reedacartwright** [comment]
Jenkins, test this please

**Comment by reedacartwright** [comment]
Jenkins, test this please

**Comment by reedacartwright** [comment]
Jenkins, test this please

**Comment by reedacartwright** [comment]
Jenkins, test this please

**Comment by reedacartwright** [comment]
Jenkins, test this please

**Pull request merged**
