### PR TITLE
Coverage flags

### PR DESCRIPTION
**Pull request by anderspitman**

### CODE REVIEW

**Comment by reedacartwright** [comment]
Jenkins, ok to test

**Comment by reedacartwright** [comment]
How does this interact with `CMAKE_BUILD_TYPE`?

Instead of setting `-O0` directly, I would prefer that it issue an error if the wrong build type is set.

**Comment by reedacartwright** [comment]
Does this work if `CXX=clang++`?

**Comment by anderspitman** [comment]
Problem with using build type is that I'm pretty sure coverage needs the debug symbols as well. Should work on `clang`

**Comment by reedacartwright** [comment]
That is simple to fix:

```
if(CMAKE_BUILD_TYPE != "Debug")
message(FATAL_ERROR ...
```

**Comment by reedacartwright** [comment]
And probably update `CMAKE_C_FLAGS_DEBUG` and `CMAKE_CXX_FLAGS_DEBUG` instead

**Comment by anderspitman** [comment]
I think I misunderstood your previous point. I thought you were saying we should `SET(CMAKE_BUILD_TYPE RELEASE)` in order to get `-O0`.

**Comment by anderspitman** [comment]
Did you mean something else?

**Comment by reedacartwright** [comment]
If this developer flag is only compatable with Debug builds, then we should throw an error if it is enabled and CMAKE_BUILD_TYPE is not equal "Debug"

**Comment by reedacartwright** [comment]
You can copy some code from here: https://github.com/denovogear/denovogear/blob/develop/CMakeLists.txt#L50-L59

**Comment by anderspitman** [comment]
But you're ok with setting `O0` manually as it currently is?

**Comment by reedacartwright** [comment]
No, leave it out. We will let the default handle that.

**Comment by reedacartwright** [comment]
Jenkins, retest this please

**Comment by anderspitman** [comment]
Looked into it a bit more and I don't think `-g` is necessary. So we should be good to do whatever build type we want as long as `-O0` is enabled.

**Comment by anderspitman** [comment]
What do you mean by default?

**Comment by reedacartwright** [comment]
`-O0` is incompatible with everything but debug builds. Here is how the CXX flags differ between build types. If you set that flag, then the non-debug builds change drasticly.

```
//Flags used by the compiler during debug builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=-g

//Flags used by the compiler during release builds for minimum
// size.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

//Flags used by the compiler during release builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the compiler during release builds with debug info.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
```

**Comment by anderspitman** [comment]
Got it. So is there any way to have `-O0` set using `CMAKE_BUILD_TYPE` or something else? It sounds like we do want to make sure the user is running the correct debug build type and then set `-O0`

**Comment by reedacartwright** [comment]
We don't need to set -O0 explicitly. That is the default and will be enabled if BUILD_TYPE=debug.

**Comment by anderspitman** [comment]
Excellent.

**Comment by anderspitman** [comment]
Weird that it's not showing your comments inline on the file. Is that a GitHub repo setting?

**Comment by anderspitman** [comment]
`CMAKE_CXX_FLAGS_DEBUG` is fine but when I set `CMAKE_C_FLAGS*` it fails when linking to gcov.  I have no idea why. Is it really necessary? Are we ever not using the C++ compiler?

**Comment by reedacartwright** [comment]
Jenkins, retest this please

**Comment by anderspitman** [comment]
Finally got this working on Jenkins with the new flag. Was getting some weird linking issues on the master node (OpenBSD). If I force it to use Ubuntu it seems to work. Not sure if it's worth tracking that issue down at the moment?

**Comment by reedacartwright** [comment]
Jenkins, retest this please.

**Comment by anderspitman** [comment]
@reedacartwright are you sure `cmake` uses `-O0` for Debug builds? If you look [here](https://github.com/Kitware/CMake/blob/e31084e65745f9dd422c6aff0a2ed4ada6918805/Modules/Compiler/GNU.cmake#L49) it appears to only append `-g`. I'm seeing strange results in the Cobertura report which I think may have to do with optimizations still being on.

**Comment by anderspitman** [comment]
Actually it appears `-O0` is the default for `gcc`.

**Comment by anderspitman** [comment]
@reedacartwright is there anything currently blocking this PR from merge? I think the rest of the coverage pipeline is in place for deployment.

**Comment by reedacartwright** [comment]
I'm too busy to look at it.

**Comment by anderspitman** [comment]
No worries. Just wanted to make sure you weren't waiting on me for anything specific.

**Comment by anderspitman** [comment]
@reedacartwright I resolved the issue I was having running coverage for `clang`. Turns out the problem was later in the pipeline with the invocation of `gcovr`. So this PR is good as it stands.

**Pull request merged**
