### PR TITLE
New treecall

### PR DESCRIPTION
**Pull request by anderspitman**

### CODE REVIEW

**Comment by reedacartwright** [comment]
Jenkins, ok to test.

**Comment by reedacartwright** [comment]
@anderspitman What is the logic of making treecall an external project?

**Comment by anderspitman** [comment]
@reedacartwright technically it isn't fully external, since it's still included in dng's source tree. But I wanted to have automatic dependency resolution in case the user doesn't have ete2 and/or pyvcf installed, so mimicking the behavior of our other external dependencies seemed like the best way. so it is using `ExternalProject_add` but pulling the source directly from a local directory. But it probably wouldn't be too hard to not use `ExternalProject_add` if that's desired.

**Comment by reedacartwright** [comment]
@anderspitman Treecall can compile and install without those dependencies installed, correct? If they are missing we should have CMake emit a warning and have dng treecall spit out an error if someone tries to run it.

**Comment by anderspitman** [comment]
@reedacartwright as the PR stands if the treecall dependencies are not installed it will try to download them from PyPI. That all happens during the `INSTALL_COMMAND` stage of `ExternalProject_add`. I'm not sure what the behavior of CMake is if that command fails. You probably have a better idea. Assuming the rest of the make commands execute, the behavior for the end user would be a python import error when attempting to run `dng treecall`. If they manually installed the missing modules it should start working.

So are you saying you don't want to attempt to automatically install the treecall dependencies? Or maybe add a separate flag for that one?

**Comment by anderspitman** [comment]
I just realized at least one update to this PR will be necessary, as the treecall dependencies are auto downloaded regardless of the value of `BUILD_EXTERNAL_PROJECTS`

**Comment by reedacartwright** [comment]
@anderspitman what is the status on this?

**Comment by anderspitman** [comment]
@reedacartwright switched efforts to coverage since that seemed like a higher priority. We need to make a few decisions on how we want this to work (some of which I outlined above) before this will be finished. Most of the hard work is done though, which was figuring out how to automatically resolve python dependencies within the context of our build system. I've also got a PR in on the treecall repo to make it easier to redistribute. Ideally we'll get to a place where we simply drop the latest treecall files into denovogear and commit.

**Comment by reedacartwright** [comment]
Once we get it into DNG all the development should happen there. I do not
think we need to keep it drop-in-able.

## 

Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute

# Arizona State University

Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign A-224A, 1-480-965-9949
Website: http://cartwrig.ht/

**Comment by anderspitman** [comment]
Oh I see. Yeah that would simplify things.

**Comment by stevenhwu** [comment]
Can one of the admin please trigger a rebuild/retest on this?
Previously we got 
==== 100% tests passed, 0 tests failed out of 29
with some errors after this

**Comment by reedacartwright** [comment]
Fix in Develop

**Pull request closed without merging**
