### PR TITLE
Feature/issue204

### PR DESCRIPTION
**Pull request by kaeldai**
Added support for ad/tad format. Refactored much of call.cc to use separate functions for vcf, sam, and tad input files. 

Also fixed an error with VCFPileup not properly filtering out extraneous columns.

### CODE REVIEW

**Comment by reedacartwright** [comment]
Jenkins, okay to test.

**Comment by kaeldai** [comment]
Please don't merge just yet. I may have found an issue I need to investigate.

**Comment by kaeldai** [comment]
@reedacartwright The Darwin13 node is a few minutes off causing the PR to fail. I'd change it myself but I don't seem to have access the machine.

When you get a chance to update the node let me know and I'll rerun the tests.

**Comment by kaeldai** [comment]
Jenkins, retest this please.

**Comment by kaeldai** [comment]
Jenkins, retest this please.

**Pull request merged**
